try:
#     # Run a non-existent command
#     result = subprocess.run(["fakecommand"], capture_output=True, text=True, check=True)
# except subprocess.CalledProcessError as e:
#     print("The command failed!")
#     print(e)